package main

import (
	"bytes"
	"flag"
	"fmt"
	// TODO: Uncomment when implementing code generation
	// "go/ast"
	// "go/format"
	// "go/parser"
	// "go/token"
	"os"
	// "strings"
	// "text/template"
)

//go:generate go run main.go -input=example.go -output=example_generated.go

// StructInfo holds information about a parsed struct
type StructInfo struct {
	Name   string
	Fields []FieldInfo
}

// FieldInfo holds information about a struct field
type FieldInfo struct {
	Name string
	Type string
	Tag  string
}

// ParseStructs parses Go source file and extracts struct definitions
func ParseStructs(filename string) ([]StructInfo, error) {
	// TODO: Implement struct parsing
	// - Create token.FileSet
	// - Parse file with parser.ParseFile
	// - Walk AST to find type declarations
	// - Extract struct definitions and fields
	// - Return slice of StructInfo
	return nil, nil
}

// GenerateBuilder generates builder pattern code for a struct
func GenerateBuilder(s StructInfo) (string, error) {
	// TODO: Implement builder generation
	// - Create builder struct type
	// - Generate setter methods for each field
	// - Generate Build() method
	// - Use text/template for code generation
	// - Return formatted Go code
	return "", nil
}

// GenerateValidation generates validation method for struct
func GenerateValidation(s StructInfo) (string, error) {
	// TODO: Implement validation generation
	// - Parse validation tags from struct fields
	// - Generate Validate() method
	// - Add validation logic for each field
	// - Return formatted Go code
	return "", nil
}

// GenerateString generates String() method for struct
func GenerateString(s StructInfo) (string, error) {
	// TODO: Implement String() method generation
	// - Generate method that returns formatted string
	// - Include all field values
	// - Return formatted Go code
	return "", nil
}

var builderTemplate = `
// {{.Name}}Builder builds {{.Name}} instances
type {{.Name}}Builder struct {
    {{range .Fields}}{{.Name}} {{.Type}}
    {{end}}
}

// New{{.Name}}Builder creates a new builder
func New{{.Name}}Builder() *{{.Name}}Builder {
    return &{{.Name}}Builder{}
}

{{range .Fields}}
// {{.Name}} sets the {{.Name}} field
func (b *{{.Name}}Builder) {{.Name}}(val {{.Type}}) *{{.Name}}Builder {
    b.{{.Name}} = val
    return b
}
{{end}}

// Build constructs the {{.Name}}
func (b *{{.Name}}Builder) Build() {{.Name}} {
    return {{.Name}}{
        {{range .Fields}}{{.Name}}: b.{{.Name}},
        {{end}}
    }
}
`

func main() {
	inputFile := flag.String("input", "", "Input Go source file")
	outputFile := flag.String("output", "", "Output file for generated code")
	flag.Parse()

	if *inputFile == "" {
		fmt.Println("Usage: go run main.go -input=file.go -output=generated.go")
		os.Exit(1)
	}

	// Parse structs from input file
	structs, err := ParseStructs(*inputFile)
	if err != nil {
		fmt.Printf("Error parsing file: %v\n", err)
		os.Exit(1)
	}

	// Generate code for each struct
	var generated bytes.Buffer
	generated.WriteString("package main\n\n")

	for _, s := range structs {
		// Generate builder
		builder, err := GenerateBuilder(s)
		if err != nil {
			fmt.Printf("Error generating builder: %v\n", err)
			continue
		}
		generated.WriteString(builder)
		generated.WriteString("\n\n")

		// Generate validation
		validation, err := GenerateValidation(s)
		if err != nil {
			fmt.Printf("Error generating validation: %v\n", err)
			continue
		}
		generated.WriteString(validation)
		generated.WriteString("\n\n")

		// Generate String method
		str, err := GenerateString(s)
		if err != nil {
			fmt.Printf("Error generating String: %v\n", err)
			continue
		}
		generated.WriteString(str)
		generated.WriteString("\n\n")
	}

	// Write output file
	if *outputFile != "" {
		if err := os.WriteFile(*outputFile, generated.Bytes(), 0644); err != nil {
			fmt.Printf("Error writing output: %v\n", err)
			os.Exit(1)
		}
		fmt.Printf("Generated code written to %s\n", *outputFile)
	} else {
		fmt.Println(generated.String())
	}
}
